// VERSION 260201
// W tym miejscu definiowane są ustawienia domyślne.
// Nie edytuj tego pliku bezpośrednio. Użyj pliku "yt-dlp.ini", aby dostosować ustawienia.

[SWITCH]

stop=0
	// 0: Użyj yt-dlp (ustawienie domyślne)  /  1: Przestań używać yt-dlp

[COOKIE]

cookie_file=
//cookie_file=%APPDATA%\PotPlayerMini64\Extension\Media\PlayParse\cookies01.txt
	// Ścieżka do zapisanego pliku cookie.
	// Konieczne jest zalogowanie się na konto w serwisie internetowym.
	// Zbierz pliki cookie z zalogowanych sesji, aby utworzyć ten plik.
	// Zobacz: https://github.com/hgcat-360/PotPlayer-Extension_yt-dlp/wiki/Get-Cookies-and-Login#prepare-a-cookie-file-manually
	// Zobacz także: https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp

cookie_browser=
//cookie_browser=firefox
	// Nazwa przeglądarki, z której mają być automatycznie pobierane pliki cookie.
	// Ignorowane, jeśli ustawiono [cookie_file].
	// Uwaga: W systemie Windows dobrze działa tylko "firefox".
	// Aby użyć profilu przeglądarki, dodaj na końcu ":PROFILE".
	// Aby użyć kontenera Firefox, dodaj na końcu "::CONTAINER".
	// Zobacz: https://github.com/hgcat-360/PotPlayer-Extension_yt-dlp/wiki/Get-Cookies-and-Login#automatically-extract-cookies

mark_watched=1
	// Dodaje obejrzane filmy do "Historii oglądania" na Twoim koncie po zalogowaniu.
	// 0: Off  /  1: On (ustawienie domyślne)

[YOUTUBE]

enable_youtube=2
	// Kontroluje sposób obsługi adresów URL w serwisie YouTube.
	// Jeśli wbudowane rozszerzenie YouTube znajduje się powyżej rozszerzenia yt-dlp,
	// to wbudowane rozszerzenie będzie obsługiwać adresy URL serwisu YouTube.
	// Jeśli jedno rozszerzenie pominie zadanie, kolejne rozszerzenie spróbuje je wykonać.
	// 0: Przekaż wszystkie adresy URL YouTube do następnego rozszerzenia
	// 1: Obsługuj filmy, przekazuj listy odtwarzania (ustawienie domyślne)
	// 2: Obsługuj zarówno filmy, jak i listy odtwarzania
	// 3: Obsługuj tylko listy odtwarzania, przekazuj filmy
	// W przypadku ustawienia 2 lub 3 zobacz [website_playlist_*] w sekcji [TARGET].
	// Niektóre listy odtwarzania mogą być traktowane inaczej niż wbudowane zachowanie.

youtube_live=0
	// Obsługuje transmisje na żywo z serwisu YouTube za pomocą yt-dlp.exe.
	// Działa tylko wtedy, gdy [enable_youtube] jest ustawione na 1 lub 2.
	// W przypadku czatu na żywo zobacz ustawienie [live_chat] w sekcji [TARGET].
	// Ustaw wartość 0, aby zamiast tego korzystać z wbudowanych funkcji PotPlayera, 
	// które umożliwiają przewijanie strumienia do punktu przed rozpoczęciem oglądania.
	// 0: Off (ustawienie domyślne)  /  1: On

base_lang=
	// Język bazowy dla etykiet menu.
	// Użyj kodu ISO 639 lub aliasu (np. "en", "pl", "pt", "fil", "iw", ...).
	// Niektóre języki wymagają podtagu regionu lub skryptu,
	// np. "zh-CN", "zh-TW", "es-419", "pt-PT", "fr-CA", "sr-Latn".
	// Nie wszystkie języki są obsługiwane w przypadku etykiet menu.
	// Leave blank for auto-detection (ustawienie domyślne).

auto_sub_lang=
//auto_sub_lang=pl, hi, en, ta, te
	// Języki automatycznie generowanych napisów w serwisie YouTube.
	// Jeśli dla tych języków istnieją automatycznie generowane napisy,
	// są one dodawane jako opcje do menu napisów w programie PotPlayer.
	// Używaj kodów ISO 639 lub aliasów. Wiele kodów należy oddzielić przecinkami.
	// Jeśli kod języka ma wiele form, dopasowywane są wszystkie
	// (np. "zh" pasuje do obu "zh-Hans" i "zh-Hant").
	// Pozostaw puste pole, aby wykrycie nastąpiło automatycznie (ustawienie domyślne).
	// Uwaga: YouTube może ograniczyć dostęp do automatycznych napisów po wielokrotnym użyciu.

dubbed_filter=1
	// Filtruje automatycznie dubbingowane ścieżki, jeśli takie istnieją.
	// Pomaga to uprościć menu jakości w PotPlayer.
	// Istnieją dwa rodzaje ścieżek z automatycznym dubbingiem: 
	// ścieżki wyłącznie audio i filmy z dubbingiem.
	// 0: Nie filtruj ścieżek z automatycznym dubbingiem
	// 1: Filtruj wszystkie automatycznie dubbingowane ścieżki według [auto_sub_lang] (ustawienie domyślne)
	// 2: Filtruj automatycznie dubbingowane ścieżki według domyślnego języka, z wyjątkiem ścieżek wyłącznie audio

keep_tab_playlist=0
	// Podczas importowania zakładek kanałów YouTube zachowuje listy odtwarzania w niezmienionej postaci.
	// Dotyczy zakładek Polecane (Strona główna), Listy odtwarzania, Wydawnictwa i Podcasty.
	// Możesz rozwinąć elementy później, klikając dwukrotnie listy odtwarzania.
	// Ustaw wartość 0, aby rozwinąć wszystkie elementy listy odtwarzania od początku.
	// Działa tylko wtedy, gdy [enable_youtube] jest ustawione na 2 lub 3,
	// a to rozszerzenie znajduje się powyżej wbudowanego rozszerzenia YouTube.
	// 0: Off (ustawienie domyślne)  /  1: On

sponsor_block=
//sponsor_block=sponsor, interaction, selfpromo, music_offtopic
//sponsor_block=all, -poi_highlight
	// Dodaje rozdziały SponsorBlock do filmów na YouTube.
	// Zobacz: https://github.com/hgcat-360/PotPlayer-Extension_yt-dlp/wiki/SponsorBlock-on-YouTube
	// Zobacz rónież: https://wiki.sponsor.ajay.app/w/Guidelines
	// Wpisz wybrane kategorie. Dostępne kategorie:
	// poi_highlight, sponsor, interaction, selfpromo, filler, hook, preview, 
	// intro, outro, music_offtopic, all. (Od wysokiego do niskiego priorytetu)
	// Oddzielaj wiele kategorii przecinkami. Przedrostek "-" oznacza wykluczenie danego elementu.

potoken_gvs=
	// poToken dla GVS (Google Video Server) na YouTube.
	// Zobacz: https://github.com/yt-dlp/yt-dlp/wiki/PO-Token-Guide
	// Format: --extractor-args "youtube:po_token=mweb.gvs+potoken_gvs"
	// Wymaga plików cookie ([cookie_file] lub [cookie_browser]).
	// Pozostaw puste pole, jeśli korzystasz z dostawcy poToken.

potoken_subs=
	// poToken dla napisów w serwisie YouTube.
	// Wymagane dla każdego filmu, jeśli brakuje napisów.
	// Zobacz: https://github.com/yt-dlp/yt-dlp/wiki/PO-Token-Guide
	// Format: --extractor-args "youtube:po_token=web.subs+potoken_subs"

#potoken_bgutil_http=
//potoken_bgutil_http="base_url=http://127.0.0.1:8080"
	// Dla dostawcy BgUtils POT.
	// Zobacz: https://github.com/Brainicism/bgutil-ytdlp-pot-provider
	// Format: --extractor-args "youtubepot-bgutilhttp:potoken_bgutil_http"
	// Wymaga plików cookie ([cookie_file] lub [cookie_browser]).

#potoken_bgutil_script=
//potoken_bgutil_script="script_path=/path/to/bgutil-ytdlp-pot-provider/server/build/generate_once.js"
	// Dla dostawcy BgUtils POT.
	// Zobacz: https://github.com/Brainicism/bgutil-ytdlp-pot-provider
	// Format: --extractor-args "youtubepot-bgutilscript:potoken_bgutil_script"
	// Wymaga plików cookie ([cookie_file] lub [cookie_browser]).

#potoken_bgutil=
//potoken_bgutil="getpot_bgutil_baseurl=https://your-app-name.herokuapp.com"
	// Dla dostawcy POT na Heroku
	// Zobacz: https://github.com/AnimMouse/yt-dlp-POT-Provider-Heroku
	// Format: --extractor-args "youtube:potoken_bgutil"
	// Wymaga plików cookie ([cookie_file] lub [cookie_browser]).

[TARGET]

website_playlist_standard=2
	// Zarządza wyodrębnianiem natywnych list odtwarzania witryny, jeśli jest to obsługiwane.
	// Po dodaniu do listy odtwarzania PotPlayera elementy są rozwijane.
	// W przypadku list odtwarzania YouTube działa tylko wtedy, gdy [enable_youtube] jest ustawione na 2 lub 3.
	// Niektóre listy odtwarzania mogą wymagać dużo czasu na zebranie metadanych elementów, 
	// więc dostosuj [playlist_metadata_timeout] zgodnie z potrzebami.
	// 0: Nie wyodrębniaj
	// 1: Wyodrębnij, jeśli adres URL jest czystą listą odtwarzania bez wideo ID (ustawienie domyślne)
	// 2: Wyodrębnij, jeśli adres URL zawiera listę odtwarzania
	// W przypadku ustawienia 2 strona może nie wyglądać jak lista odtwarzania.

website_playlist_each=youtube:1, youtu.be:1, bilibili.com:2
	// Obsługuje listy odtwarzania stron internetowych dla poszczególnych witryn.
	// Ma pierwszeństwo przed [website_playlist_standard].
	// Format: "key:value," gdzie klucz jest ciągiem znaków w domenie adresu URL, 
	// a wartość (0, 1, 2) ma takie samo znaczenie jak w [website_playlist_standard].

playlist_items_timeout=0
	// Czas odniesienia w sekundach dla zbierania elementów listy odtwarzania.
	// Po upływie tego czasu proces zostaje zatrzymany, więc wyświetla się mniej elementów.
	// W przypadku dużych list odtwarzania prędkość przetwarzania jest znacznie wolniejsza, jeśli ustawiono limit czasu.
	// Ustaw na 0, aby nie stosować ograniczeń (ustawienie domyślne).

playlist_metadata_timeout=30
	// Czas odniesienia w sekundach dla gromadzenia metadanych elementów listy odtwarzania.
	// Po upływie tego czasu gromadzenie metadanych zostaje zatrzymane, a elementy są wyświetlane od razu.
	// Ten limit czasu nie jest stosowany, gdy elementy wczytują się szybko w niektórych witrynach internetowych.
	// Domyślna wartość to 30. Ustaw wartość 0, aby usunąć ograniczenie. 

playlist_without_metadata=1
	// Wyświetla elementy z list odtwarzania witryny internetowej, 
	// nawet jeśli ich metadane nie zostały jeszcze zebrane.
	// Jeśli [playlist_metadata_timeout] jest zbyt krótki, 
	// w liście odtwarzania PotPlayera może pojawić się wiele pozycji bez tytułu.
	// 0: Off  /  1: On (ustawienie domyślne)

direct_file_info=1
	// Ustawia metadane dla bezpośrednich linków do plików wideo, audio lub obrazów w sieci.
	// (data i domena serwera, wraz z miniaturą z samego pliku)
	// yt-dlp.exe nie będzie używany w tym zadaniu.
	// Uwaga: Wykrywanie rzeczywistego pliku nie zawsze jest dokładne.
	// 0: Off  /  1: On (ustawienie domyślne)

m3u8_hls=1
	// Wykorzystuje plik yt-dlp.exe dla plików M3U8 (*.m3u8) w sieci, które zawierają tagi HLS.
	// Pobiera wybrane formaty jakości w strumieniu, jeśli są dostępne.
	// Pliki HLS M3U8 są zazwyczaj odtwarzane jako pojedynczy strumień.
	// Jeśli ustawiono wartość 2, elementy są rozwijane po dodaniu do listy odtwarzania PotPlayer.
	// 0: Nie obsługuj plików M3U8
	// 1: Obsługa HLS M3U8 jako pojedynczego strumienia (ustawienie domyślne)
	// 2: W razie potrzeby obsługuj i rozwijaj elementy z M3U8

live_chat=1
	// Obsługuje czat na żywo. Obsługuje serwisy YouTube, Twitch, Kick i Rumble.
	// Można go wyświetlić za pomocą domyślnego klawisza [F9]. 
	// Korzystanie z czatu na żywo uruchamia wewnętrzną przeglądarkę Edge (WebView2) programu PotPlayer.
	// Jeśli [youtube_live] jest ustawione na 0, to ustawienie jest ignorowane dla serwisu YouTube.
	// Aby dołączyć do czatu na YouTube Live, zaloguj się na swoje konto:
	// [Preferencje] > [Rozszerzenia] > [Konto internetowe]
	// 0: Off  /  1: On (ustawienie domyślne)

rss_playlist=1
	// Wykorzystuje plik yt-dlp.exe do obsługi kanałów RSS w Internecie, zazwyczaj kończących się rozszerzeniem ".xml".
	// Wyodrębnia i importuje wymienione elementy do listy odtwarzania PotPlayer 
	// po dodaniu adresu URL kanału RSS.
	// 0: Off  /  1: On (ustawienie domyślne)

radio_info=1
	// Zbiera metadane dotyczące radia internetowego (nazwa stacji, itp.).
	// Obsługiwane są Shoutcast i Icecast.
	// To rozszerzenie obsługuje metadane radiowe bezpośrednio, bez użycia pliku yt-dlp.exe.
	// Uwaga: Dynamiczne tytuły utworów są wyświetlane dzięki wbudowanej funkcji programu PotPlayer.
	// 0: Off  /  1: On (ustawienie domyślne)

shoutcast_playlist=0
	// Obsługuje listy odtwarzania Shoutcast bezpośrednio, bez rozwijania elementów.
	// (pliki PLS, M3U, XSPF -- tunein-station z http://yp.shoutcast.com/)
	// Pobiera nazwy stacji i, jeśli są dostępne, opcje serwera, które można wybrać.
	// yt-dlp.exe nie działa z listami odtwarzania Shoutcast.
	// Jeśli ustawiono wartość 0, rozszerza adresy URL serwerów po dodaniu do listy odtwarzania PotPlayer.
	// 0: Off (ustawienie domyślne)  /  1: On

[FORMAT]

reduce_formats=0
	// Zmniejsza liczbę formatów, gdy w menu jakości pojawia się ich wiele.
	// Pomaga to uprościć menu jakości w PotPlayer.
	// Ustawienie 1 jest przydatne w przypadku nieograniczonego dostępu szerokopasmowego.
	// 0: Nie zmniejszaj (ustawienie domyślne)
	// 1: Zmniejsz liczbę niskiej jakości
	// 2: Zmniejsz liczbę wysokiej jakości
	// 3: Filtruj według rozdzielczości od SD do FullHD

remove_duplicate_quality=1
	// Ukrywa formaty o zduplikowanej jakości i typie w menu jakości.
	// 0: Off  /  1: On (ustawienie domyślne)

live_as_vod=0
	// Próbuje odtwarzać transmisje na żywo w formie VOD (wideo na żądanie).
	// Działa tylko w niektórych transmisjach na Twitchu.
	// Niektóre metadane mogą ulec zmianie, a reklamy mogą zostać usunięte.
	// Jeżeli to się nie powiedzie, yt-dlp.exe zostanie uruchomiony ponownie w normalny sposób.
	// Uwaga: Nie można cofnąć do początku transmisji na żywo.
	// 0: Off (ustawienie domyślne)  /  1: On

live_prefix="{LIVE} "
//live_prefix="[ON AIR] "
	// Tekst na początku tytułów transmisji na żywo.
	// Do transmisji na żywo na poszczególnych kanałach.
	// Użyj cudzysłowów, aby zachować spację na końcu.

radio_thumbnail=1
	// Wyświetla miniatury obrazów dla radia internetowego w panelu listy odtwarzania.
	// Pliki graficzne (yt-dlp_radio*.jpg) muszą być umieszczone w folderze skryptu.
	// 0: Off  /  1: On (ustawienie domyślne)

more_detailed_title=1
	// Używa "alt_title", jeśli jest bardziej szczegółowy niż tytuł domyślny.
	// 0: Off  /  1: On (ustawienie domyślne)

title_multi_lines=0
	// Zachowuje tytuły w wielu wierszach, jeśli zawierają znaki końca wiersza.
	// Tytuły wielowierszowe są łatwiejsze do odczytania w dymku.
	// 0: Off (ustawienie domyślne)  /  1: On

title_max_length=250
	// Maksymalna długość tytułu strumienia.
	// Jeśli tytuł jest dłuższy niż ta wartość, zostanie skrócony.
	// Ustaw na 0, aby nie stosować ograniczeń (Domyślnie: 250, Dopuszczalna minimalna wartość: 30).

[NETWORK]

proxy=
//proxy=socks5://user:pass@127.0.0.1:1080/
	// Proxy address for HTTP/HTTPS/SOCKS.

#socket_timeout=

#source_address=

#geo_verification_proxy=

#xff=

ip_version=0
	// Wersja IP do wykorzystania we wszystkich połączeniach
	// 0: Domyślne
	// 4: IPv4
	// 6: IPv6

no_check_certificates=1
	// Wyłącza sprawdzanie certyfikatu HTTPS.
	// Umożliwia dostęp nawet jeśli certyfikat serwera wygasł.
	// 0: Off  /  1: On (ustawienie domyślne)

referer=
	// Odnośnik URL.
	// Używane tylko wtedy, gdy dostęp do yt-dlp jest zabroniony.

[MAINTENANCE]

console_out=0
	// Wyświetla okno konsoli z komunikatami i błędami.
	// Aby zamknąć, ustaw tę opcję na 0 i uruchom ponownie PotPlayer.
	// Ostrzeżenie: Podczas zaznaczania tekstu w konsoli rozszerzenia przestają działać.
	// Zobacz: https://github.com/hgcat-360/PotPlayer-Extension_yt-dlp/wiki/Console-Log-Output-Notes
	// 0: Ukryj (domyślnie)
	// 1: Pokaż główne informacje
	// 2: Pokaż szczegółowe informacje
	// 3: Pokaż wszystkie informacje z danymi JSON yt-dlp i serwera HTTP

ytdlp_location=C:\Program Files\DAUM\PotPlayer\Extension\Data\yt-dlp_win\
	// Ścieżka folderu, w którym należy umieścić plik yt-dlp.exe.
	// Wprowadź pełną ścieżkę do folderu bez zmiennych środowiskowych.
	// Jeśli pole jest puste, używany jest folder "Module" PotPlayer (ustawienie domyślne).

update_ytdlp=0
	// Automatycznie aktualizuje plik yt-dlp.exe, jeśli w sieci zostanie znaleziona nowsza wersja.
	// W przypadku korzystania z kompilacji nocnej pobierana jest najnowsza wersja nocna.
	// Mogą być konieczne uprawnienia administratora, aby PotPlayer mógł zastąpić plik yt-dlp.exe.
	// Możesz zmienić folder [ytdlp_location], aby uzyskać uprawnienia do zapisu.
	// 0: Nie aktualizuj automatycznie (ustawienie domyślne)
	// 1: Automatyczna aktualizacja podczas korzystania z rozszerzenia yt-dlp
	// 2: Zaktualizuj raz, a następnym razem otwórz panel informacyjny yt-dlp w ustawieniach

ytdlp_hash=
	// Wartość hash pliku yt-dlp.exe.
	// Nie usuwaj tego.

critical_error=0
	// Jeśli pojawi się błąd krytyczny, sprawdź czy plik yt-dlp.exe jest oryginalny.
	// Jeśli jest to bezpieczne, ustaw tę opcję na 0 i ponownie wczytaj rozszerzenia.

